#' Get DRI (individual)
#'
#' @param ic dataframe generated by get_dri_ic(data)
#'
#' @returns dataframe with individual DRI
#' @export
#' @import dplyr
#' @import tibble
#' @examples
#' get_dri_ind(ic)
get_dri_ind <- function(ic) {
  # tracks return value
  dri_ind <- list()

  # iterate through all pnums
  for (pi in union(ic$pnum1, ic$pnum2)) {
    # STEP 1: get data for pnum i
    pi_data <- ic %>% filter(pnum1 == pi | pnum2 == pi)

    # STEP 2: calculate distance
    pi_di <- mean(pi_data$dj)

    # STEP 3: calculate individual dri
    lambda <- sqrt(2) / 2
    pi_dri <- ((-2 * pi_di) + lambda) / lambda
    dri_ind[[length(dri_ind) + 1]] <- tibble(pnum = pi, dri = pi_dri)

  }

  return(bind_rows(dri_ind))

}
