#' Get DRI (group)
#'
#' @param ic dataframe generated by get_dri_ic(data)
#' @param adjusted boolean flag indicates whether to use updated or original DRI
#' formula (default = TRUE)
#'
#' @returns the group-level DRI value
#' @export
#'
#' @examples
#' get_dri(ic)
get_dri <- function(ic, adjusted = TRUE){

  # scalar penalty based on strength of signal (|ccor| and |pcor|)
  if (adjusted) {
    max_cor <- pmax(abs(ic$ccor), abs(ic$pcor))
    penalty <- ifelse(max_cor <= 0.2, max_cor / 0.2, 1)
    dist <- 1 - mean((1 - ic$dj) * penalty)
  } else {
    dist <- mean(ic$dj)
  }

  lambda <- sqrt(2) / 2
  dri <- ((-2 * dist) + lambda) / lambda
  return(dri)
}
