#' Get DRI (individual)
#'
#' @param ic dataframe generated by get_dri_ic(data)
#' @param adjusted a logical indicating whether you want the original or adjusted
#' DRI formula
#'
#' @returns dataframe with individual DRI
#' @export
#' @import dplyr
#' @import tibble
#' @importFrom rlang .data
#' @examples
#'
#' library(tibble)
#' data <- tibble(
#'   pnum = c(1,2,3,4),
#'   C1 = c(1,2,3,4),
#'   C2 = c(2,3,4,3),
#'   C3 = c(3,2,4,2),
#'   C4 = c(4,3,3,1),
#'   P1 = c(1,2,3,3),
#'   P2 = c(2,3,1,2),
#'   P3 = c(3,1,2,1),
#' )
#'
#' ic <- get_dri_ic(data)
#' get_dri_ind(ic)
get_dri_ind <- function(ic, adjusted = TRUE) {
  # tracks return value
  dri_ind <- list()

  # iterate through all pnums
  for (pi in union(ic$pnum1, ic$pnum2)) {
    # STEP 1: get data for pnum i
    pi_ic <- ic %>% filter(.data$pnum1 == pi | .data$pnum2 == pi)

    # use DRI formula to calculate DRI
    pi_dri <- get_dri(pi_ic, adjusted)

    # # STEP 2: calculate distance
    # pi_di <- mean(pi_ic$dj)
    #
    # # STEP 3: calculate individual dri
    # lambda <- sqrt(2) / 2
    # pi_dri <- ((-2 * pi_di) + lambda) / lambda
    dri_ind[[length(dri_ind) + 1]] <- tibble(pnum = pi, dri = pi_dri)

  }

  return(bind_rows(dri_ind))

}
