#' Plot DRI IC
#'
#' @param ic dataframe generated by get_dri_ic(data)
#' @param title title of the plot (default = NA)
#' @param suffix string pre, post (default = NA)
#' @param dri numeric value (default = NA)
#' @import ggplot2 grid
#'
#' @returns plot
#' @export
#'
#' @examples
#'
#' library(tibble)
#' data <- tibble(
#'   pnum = c(1,2,3,4),
#'   C1 = c(1,2,3,4),
#'   C2 = c(2,3,4,3),
#'   C3 = c(3,2,4,2),
#'   C4 = c(4,3,3,1),
#'   P1 = c(1,2,3,3),
#'   P2 = c(2,3,1,2),
#'   P3 = c(3,1,2,1),
#' )
#'
#' ic <- get_dri_ic(data)
#' plot_dri_ic(ic)
plot_dri_ic <- function(ic,
                     title = NA,
                     suffix = NA,
                     dri = NA) {

  # create title
  plot_title <- if (!is.na(title)) title else "IC Plot"
  plot_title <- if (!is.na(suffix)) paste0(plot_title, ": ", suffix) else plot_title

  # create a DRI annotation
  grob <- grobTree(textGrob(
    paste0("DRI = ", round(dri, 3)),
    x = 0.1,
    y = 0.9,
    hjust = 0,
    gp = gpar(
      col = "red",
      fontsize = 13,
      fontface = "italic"
    )
  ))

  plot <-
    ggplot(ic, aes(x = ccor, y = pcor)) +
    geom_jitter(
      width = 0.02,
      height = 0.02,
      show.legend = TRUE,
      col = rgb(0.1, 0, 1, 0.6),
      lwd = 3
    ) +
    xlim(-1.1, 1.1) + ylim(-1.1, 1.1) +
    theme(panel.grid.major = element_blank(),
          panel.grid.minor = element_blank()) +
    geom_abline(
      intercept = 0,
      slope = 1,
      colour = "white",
      lwd = 1
    ) +
    geom_hline(yintercept = 0,
               color = "white",
               lwd = 1) +
    geom_vline(xintercept = 0,
               color = "white",
               lwd = 1) +
    labs(x = "Intersubjective Agreement - Considerations", y = "Intersubjective Agreement - Preferences") +
    ggtitle(plot_title) +
    annotation_custom(grob) +
    geom_density_2d_filled(inherit.aes = T, alpha = 0.3) +
    geom_density_2d(colour = "black") +
    theme(legend.position = "none")

  return(plot)
}
